/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.2/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "Zenith"

include(":zenith-core")
include(":zenith-config")
include(":zenith-base")
include(":zenith-commands-common")
include(":zenith-commands-bukkit")
include(":zenith-dependency-common")
include(":zenith-dependency-bukkit")
include(":zenith-integrations")
include(":zenith-items")
//include(":zenith-custom")
//include(":zenith-database")

project(":zenith-core").projectDir = file("packages/core")
project(":zenith-config").projectDir = file("packages/config")
project(":zenith-base").projectDir = file("packages/base")
//project(":zenith-commands").projectDir = file("packages")
project(":zenith-commands-common").projectDir = file("packages/commands-common")
project(":zenith-commands-bukkit").projectDir = file("packages/commands-bukkit")
//project(":zenith-dependency").projectDir = file("packages")
project(":zenith-dependency-common").projectDir = file("packages/dependency-common")
project(":zenith-dependency-bukkit").projectDir = file("packages/dependency-bukkit")
project(":zenith-integrations").projectDir = file("packages/integrations")
project(":zenith-items").projectDir = file("packages/items")
//project(":zenith-custom").projectDir = file("packages/custom")
//project(":zenith-database").projectDir = file("packages/database")


print("Finished Building: ")
println(rootProject)

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven {
            url = uri("https://jitpack.io") 
        }
        maven {
            url = uri("https://hub.spigotmc.org/nexus/content/groups/public/")
        }
        maven {
            url = uri("http://nexus.hc.to/content/repositories/pub_releases")
            isAllowInsecureProtocol = true
        }

        maven {
            url = uri("https://repo.codemc.org/repository/maven-public")
        }

        // PlaceholderAPI
        maven {
            url = uri("https://repo.extendedclip.com/releases/")
        }

        maven {
            url = uri("https://repo.maven.apache.org/maven2/")
        }

        // EngineHub
        maven {
            url = uri("https://maven.enginehub.org/repo/")
        }

        // EssentialsX
        maven {
            url = uri("https://repo.essentialsx.net/releases/")
        }

        // Paper
        maven {
            url = uri("https://papermc.io/repo/repository/maven-public/")
        }

        maven {
            url = uri("https://nexus.scarsz.me/content/groups/public/")
        }

        maven {
            url = uri("https://oss.sonatype.org/repository/releases/")
        }
        maven {
            url = uri("https://repo.codemc.io/repository/creatorfromhell/")
        }
        // Oraxon
        maven {
            url = uri("https://repo.oraxen.com/releases")
        }
        maven {
            url = uri("https://maven.devs.beer/")
        }
        maven {
            url = uri("https://repo.viaversion.com")
        }
    }
}
